services:
  Fiedsch\RemoteListingBundle\Controller\ContentElement\RemoteListingController:
    public: true
    arguments:
      - '@doctrine.dbal.remote_connection'
    tags:
      -
        name: contao.content_element
        category: remotelisting
        type: remotelisting
        template: ce_remotelisting
        renderer: esi
